/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Cleanup old caches
cleanupOutdatedCaches();

// Take control of all clients immediately
self.skipWaiting();
clientsClaim();

// Handle the share target POST request
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Check if this is the share target action and a POST request
  if (event.request.method === 'POST' && url.pathname === '/') {
    event.respondWith(
      (async () => {
        const formData = await event.request.formData();
        const file = formData.get('file');

        // Redirect to / with a search parameter to indicate a shared file
        // We'll use this to trigger the app to listen for the file
        const response = Response.redirect('/?share-target=true', 303);

        if (file instanceof File) {
          // Store the file temporarily or use BroadcastChannel to send it to the client
          // Since we are redirecting, the new client might not be ready yet.
          // We can use a short-lived cache or IndexedDB, but a BroadcastChannel 
          // combined with a small delay or a "ready" message from the client is often enough.
          
          // Wait for the client to be ready
          const broadcast = new BroadcastChannel('share-target');
          
          broadcast.onmessage = (event) => {
            if (event.data === 'READY') {
              broadcast.postMessage({ file, fileName: file.name });
            }
          };

          // Also send it immediately with a delay just in case
          setTimeout(() => {
            broadcast.postMessage({ file, fileName: file.name });
          }, 2000);
        }

        return response;
      })()
    );
  }
});
